version: "3.9"
services:
  nginx_con:
    image: nginx:1.23-alpine

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./prod_settings/nginx-https.conf:/etc/nginx/conf.d/default.conf"
      - "./entrypoint.sh:/entrypoint.sh"
      - "/etc/ssl/private/nginx_test.key:/etc/ssl/private/nginx_test.key"
      - "/etc/ssl/certs/nginx_test.crt:/etc/ssl/certs/nginx_test.crt"

    depends_on:
      - flask_con
    #user: root
    #command: chmod +x /entrypoint.sh
    #entrypoint: /entrypoint.sh

  flask_con:
    image: python:3.9.16-alpine3.16
    volumes:
      - "./app.py:/app/app.py"
      - "./req.txt:/app/req.txt"

    expose:
      - "5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    working_dir: /app
    command: sh -c "
      apk add --no-cache gcc musl-dev linux-headers  &&
      pip install -r req.txt && 
      gunicorn --bind 0.0.0.0:5000 --workers=3 app:app"

